spring:
  application:
    name: microsb-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: MANUAL
        default-requeue-rejected: false
        retry:
          enabled: false # Desabilita retry autom√°tico, usamos manual
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

app:
  rabbitmq:
    queues:
      main: "products.queue"
      retry5s: "products.retry.5s.queue"
      dead: "products.dead.queue"
    exchanges:
      main: "products.exchange"
      dlx: "products.dlx"
    routing-keys:
      created: "products.created"
      retry5s: "products.retry.5s"
      dead: "products.dead"
    retry:
      max-attempts: 3
      retry-delay-ms: 5000

server:
  port: 8081