spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/microsa
    username: microsa
    password: microsa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # em prod: validate (ou none) — nada de create/update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
      open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated # Habilita confirmações (ConfirmCallback)
    publisher-returns: true # Habilita retorno de mensagens não roteadas (ReturnsCallback)

app:
  rabbitmq:
    exchanges:
      main: "products.exchange"
    routing-keys:
      created: "products.created"
      updated: "products.updated"
      deleted: "products.deleted"

server:
  port: 8080




